-- MySQL Script generated by MySQL Workbench
-- 11/04/14 22:28:25
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gtracer
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gtracer
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gtracer` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `gtracer` ;

-- -----------------------------------------------------
-- Table `gtracer`.`graduate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gtracer`.`graduate` (
  `student_no` VARCHAR(10) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `midname` VARCHAR(45) NULL,
  `sex` VARCHAR(6) NOT NULL,
  `bdate` DATE NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `mobileno` INT(11) NOT NULL,
  `telno` INT(8) NULL,
  `field` VARCHAR(45) NOT NULL,
  `major` VARCHAR(45) NULL,
  `graduatedate` CHAR(6) NOT NULL,
  PRIMARY KEY (`student_no`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gtracer`.`work`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gtracer`.`work` (
  `workid` INT NOT NULL AUTO_INCREMENT,
  `studentno` VARCHAR(10) NOT NULL,
  `position` VARCHAR(45) NOT NULL,
  `companyname` VARCHAR(60) NOT NULL,
  `companyaddress` VARCHAR(100) NULL,
  `salary` INT NULL,
  `supervisor` TINYINT(1) NULL,
  `companytype` TINYINT(1) NOT NULL COMMENT 'private-0 (including self-employed)\ngovernment-1',
  `employmentstatus` VARCHAR(45) NULL COMMENT 'values check box on UI :)\nregular or permanent, temporary, casual, contractual, self-employed',
  PRIMARY KEY (`workid`),
  KEY `studentno` (`studentno`),
  INDEX `fk_work_graduate_idx` (`studentno` ASC),
  CONSTRAINT `fk_work_graduate`
    FOREIGN KEY (`studentno`)
    REFERENCES `gtracer`.`graduate` (`student_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gtracer`.`grant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gtracer`.`grant` (
  `studentno` VARCHAR(10) NOT NULL,
  `grantname` VARCHAR(45) NOT NULL,
  `grantor` VARCHAR(45) NULL,
  `granttype` VARCHAR(45) NULL COMMENT '* personal\n* government\n* others',
  PRIMARY KEY (`studentno`),
  CONSTRAINT `fk_grant_graduate1`
    FOREIGN KEY (`studentno`)
    REFERENCES `gtracer`.`graduate` (`student_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gtracer`.`publication`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gtracer`.`publication` (
  `publicationno` INT NOT NULL AUTO_INCREMENT,
  `studentno` VARCHAR(20) NOT NULL,
  `publicationtitle` VARCHAR(60) NOT NULL,
  `publicationdate` DATE NOT NULL,
  `publicationdesc` VARCHAR(300) NULL,
  PRIMARY KEY (`publicationno`),
  KEY `studentno` (`studentno`),
  INDEX `fk_publication_graduate1_idx` (`studentno` ASC),
  CONSTRAINT `fk_publication_graduate1`
    FOREIGN KEY (`studentno`)
    REFERENCES `gtracer`.`graduate` (`student_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gtracer`.`skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gtracer`.`skill` (
  `studentno` VARCHAR(10) NOT NULL,
  `skill` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`studentno`, `skill`),
  INDEX `fk_skill_graduate1_idx` (`studentno` ASC),
  CONSTRAINT `fk_skill_graduate1`
    FOREIGN KEY (`studentno`)
    REFERENCES `gtracer`.`graduate` (`student_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gtracer`.`talent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gtracer`.`talent` (
  `studentno` VARCHAR(10) NOT NULL,
  `talent` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`studentno`, `talent`),
  INDEX `fk_talent_graduate1_idx` (`studentno` ASC),
  CONSTRAINT `fk_talent_graduate1`
    FOREIGN KEY (`studentno`)
    REFERENCES `gtracer`.`graduate` (`student_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gtracer`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gtracer`.`project` (
  `studentno` VARCHAR(10) NOT NULL,
  `projecttitle` VARCHAR(60) NOT NULL,
  `projectdesc` VARCHAR(300) NULL,
  PRIMARY KEY (`studentno`, `projecttitle`),
  CONSTRAINT `fk_project_graduate1`
    FOREIGN KEY (`studentno`)
    REFERENCES `gtracer`.`graduate` (`student_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gtracer`.`educationalbg`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gtracer`.`educationalbg` (
  `bgno` INT NOT NULL AUTO_INCREMENT,
  `studentno` VARCHAR(10) NOT NULL,
  `school` VARCHAR(50) NOT NULL,
  `yearstart` YEAR NOT NULL,
  `yearend` YEAR NOT NULL,
  `level` VARCHAR(45) NOT NULL COMMENT 'primary, secondary, tertiary',
  `graduate` TINYINT(1) NULL COMMENT '1 - graduated\n0 - not',
  `course` VARCHAR(45) NULL COMMENT 'if level is tertiary, course is required\n\nthis includes masters and doctorate degrees',
  PRIMARY KEY (`bgno`, `studentno`),
  CONSTRAINT `fk_educationalbg_graduate1`
    FOREIGN KEY (`studentno`)
    REFERENCES `gtracer`.`graduate` (`student_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gtracer`.`honor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gtracer`.`honor` (
  `studentno` VARCHAR(10) NOT NULL,
  `bgno` INT NOT NULL,
  `honor` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`studentno`, `bgno`, `honor`),
  INDEX `fk_honor_educationalbg1_idx` (`bgno` ASC),
  CONSTRAINT `fk_honor_educationalbg1`
    FOREIGN KEY (`bgno`)
    REFERENCES `gtracer`.`educationalbg` (`bgno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_honor_educationalbg2`
    FOREIGN KEY (`studentno`)
    REFERENCES `gtracer`.`educationalbg` (`studentno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gtracer`.`profexam`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gtracer`.`profexam` (
  `studentno` VARCHAR(10) NOT NULL,
  `profexamname` VARCHAR(60) NOT NULL,
  `datetaken` DATE NOT NULL,
  `rating` DECIMAL NOT NULL,
  PRIMARY KEY (`studentno`, `profexamname`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
