-- MySQL Script generated by MySQL Workbench
-- 11/14/14 23:55:54
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`graduate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`graduate` (
  `student_no` VARCHAR(10) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `midname` VARCHAR(45) NULL,
  `sex` VARCHAR(6) NOT NULL,
  `bdate` DATE NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `mobileno` INT(11) NOT NULL,
  `telno` INT(8) NULL,
  `field` VARCHAR(45) NOT NULL,
  `major` VARCHAR(45) NULL,
  `graduatedate` CHAR(6) NOT NULL,
  PRIMARY KEY (`student_no`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`companies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`companies` (
  `idcompanies` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NULL,
  PRIMARY KEY (`idcompanies`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`work`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`work` (
  `workid` INT NOT NULL AUTO_INCREMENT,
  `studentno` VARCHAR(10) NOT NULL,
  `position` VARCHAR(45) NOT NULL,
  `companyname` VARCHAR(255) NOT NULL,
  `companyaddress` VARCHAR(255) NULL,
  `salary` INT NULL,
  `supervisor` TINYINT(1) NULL,
  `companytype` TINYINT(1) NOT NULL COMMENT 'private-0 (including self-employed)' /* comment truncated */ /*government-1*/,
  `employmentstatus` VARCHAR(45) NULL COMMENT 'values check box on UI :)' /* comment truncated */ /*regular or permanent, temporary, casual, contractual, self-employed*/,
  PRIMARY KEY (`workid`, `studentno`),
  INDEX `fk_work_graduate_idx` (`studentno` ASC),
  CONSTRAINT `fk_work_graduate`
    FOREIGN KEY (`studentno`)
    REFERENCES `mydb`.`graduate` (`student_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_work_companies`
    FOREIGN KEY (`workid`)
    REFERENCES `mydb`.`companies` (`idcompanies`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`grant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`grant` (
  `studentno` VARCHAR(10) NOT NULL,
  `grantname` VARCHAR(45) NOT NULL,
  `grantor` VARCHAR(45) NULL,
  `granttype` VARCHAR(45) NULL COMMENT '* personal' /* comment truncated */ /** government
* others*/,
  PRIMARY KEY (`studentno`),
  CONSTRAINT `fk_grant_graduate1`
    FOREIGN KEY (`studentno`)
    REFERENCES `mydb`.`graduate` (`student_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`publication`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`publication` (
  `studentno` VARCHAR(20) NOT NULL,
  `publicationno` INT NOT NULL AUTO_INCREMENT,
  `publicationtitle` VARCHAR(60) NOT NULL,
  `publicationdate` DATE NOT NULL,
  `publicationdesc` VARCHAR(300) NULL,
  PRIMARY KEY (`studentno`, `publicationno`),
  INDEX `fk_publication_graduate1_idx` (`studentno` ASC),
  CONSTRAINT `fk_publication_graduate1`
    FOREIGN KEY (`studentno`)
    REFERENCES `mydb`.`graduate` (`student_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`skill` (
  `studentno` VARCHAR(10) NOT NULL,
  `skill` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`studentno`, `skill`),
  INDEX `fk_skill_graduate1_idx` (`studentno` ASC),
  CONSTRAINT `fk_skill_graduate1`
    FOREIGN KEY (`studentno`)
    REFERENCES `mydb`.`graduate` (`student_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`talent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`talent` (
  `studentno` VARCHAR(10) NOT NULL,
  `talent` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`studentno`, `talent`),
  INDEX `fk_talent_graduate1_idx` (`studentno` ASC),
  CONSTRAINT `fk_talent_graduate1`
    FOREIGN KEY (`studentno`)
    REFERENCES `mydb`.`graduate` (`student_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`project` (
  `studentno` VARCHAR(10) NOT NULL,
  `projecttitle` VARCHAR(60) NOT NULL,
  `projectdesc` VARCHAR(300) NULL,
  PRIMARY KEY (`studentno`, `projecttitle`),
  CONSTRAINT `fk_project_graduate1`
    FOREIGN KEY (`studentno`)
    REFERENCES `mydb`.`graduate` (`student_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`schools`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`schools` (
  `idschools` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idschools`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`educationalbg`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`educationalbg` (
  `studentno` VARCHAR(10) NOT NULL,
  `bgno` INT NOT NULL AUTO_INCREMENT,
  `school` VARCHAR(50) NOT NULL,
  `yearstart` YEAR NOT NULL,
  `yearend` YEAR NOT NULL,
  `level` VARCHAR(45) NOT NULL COMMENT 'primary, secondary, tertiary',
  `graduate` TINYINT(1) NULL COMMENT '1 - graduated' /* comment truncated */ /*0 - not*/,
  `course` VARCHAR(45) NULL COMMENT 'if level is tertiary, course is required' /* comment truncated */ /*
this includes masters and doctorate degrees*/,
  PRIMARY KEY (`bgno`, `studentno`),
  CONSTRAINT `fk_educationalbg_graduate1`
    FOREIGN KEY (`studentno`)
    REFERENCES `mydb`.`graduate` (`student_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_educationalbg_schools`
    FOREIGN KEY (`bgno`)
    REFERENCES `mydb`.`schools` (`idschools`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`honor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`honor` (
  `studentno` VARCHAR(10) NOT NULL,
  `bgno` INT NOT NULL,
  `honor` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`studentno`, `bgno`, `honor`),
  INDEX `fk_honor_educationalbg1_idx` (`bgno` ASC),
  CONSTRAINT `fk_honor_educationalbg1`
    FOREIGN KEY (`bgno`)
    REFERENCES `mydb`.`educationalbg` (`bgno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_honor_educationalbg2`
    FOREIGN KEY (`studentno`)
    REFERENCES `mydb`.`educationalbg` (`studentno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`profexam`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`profexam` (
  `studentno` VARCHAR(10) NOT NULL,
  `profexamname` VARCHAR(60) NOT NULL,
  `datetaken` DATE NOT NULL,
  `rating` DECIMAL NOT NULL,
  PRIMARY KEY (`studentno`, `profexamname`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`update`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`update` (
  `studentno` VARCHAR(10) NOT NULL,
  `updateindex` INT NULL AUTO_INCREMENT,
  `body` VARCHAR(255) NOT NULL,
  `time` DATETIME NOT NULL,
  `author` VARCHAR(140) NULL,
  PRIMARY KEY (`studentno`),
  CONSTRAINT `fk_post_graduate1`
    FOREIGN KEY (`studentno`)
    REFERENCES `mydb`.`graduate` (`student_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
